spring:
  application:
    name: demo
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/spring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
